# Generated by Django 3.0.3 on 2020-03-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_title', models.CharField(max_length=50, verbose_name='название объекта')),
                ('sight_description', models.TextField(verbose_name='описание объекта')),
                ('sight_lat', models.FloatField(verbose_name='широта')),
                ('sight_lon', models.FloatField(verbose_name='долгота')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=500, upload_to='', verbose_name='изображение объекта', width_field=500)),
                ('img_text', models.CharField(max_length=50, verbose_name='комментарии к изображению')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sights.Sight')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
