# Generated by Django 3.0.3 on 2020-03-10 23:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_auto_20200310_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='', verbose_name='изображение объекта'),
        ),
    ]
